
name: 'dbt_duckdb_parquet_to_mysql'
version: '1.0.0'
config-version: 2

profile: 'dbt_duckdb_parquet_to_mysql'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_duckdb_parquet_to_mysql:
    materialized: table
    database: mysql
    schema: app_schema
    staging:
      database: dbt
      schema: main
      materialized: table
