version: 2

models:
  - name: dbt_customers
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: bigint
        constraints:
          - type: not_null
          - type: primary_key
      - name: first_name
        data_type: text
        constraints:
          - type: not_null
      - name: last_name
        data_type: text
        constraints:
          - type: not_null